-- Category taxonomy: the list of report lines a transaction can be classified
-- into. Change 3.1, capability `classification-taxonomy`.
--
-- This is the first table in the schema that is shared and tenant at once, and
-- that single property drives every decision below.
--
-- Its top two levels are accounting structure -- NET SALES, OPEX >
-- Administration, and the arithmetic that turns them into GM. They must be
-- identical for every customer or reports stop being comparable and the
-- formulas stop being trustworthy. Its leaves are particular to a business:
-- "IT Park - membership" is a Belarusian residency scheme, "Merch for
-- employees" is one company's habit. Twenty nodes are shared, eighty-one are
-- not.
--
-- So org_id is NULL on a shared row, and the read policy admits a row that is
-- shared *or* mine while the write policy admits only mine. Splitting them is
-- the whole point: one FOR ALL policy saying `org_id IS NULL OR org_id =
-- app_current_org()` would let vekst_app rewrite GM's formula for every
-- customer at once.
--
-- Content comes from eval/out/seed_categories.sql, generated by eval/emit.py
-- from the founder's P&L structure and the three categorisation files, and
-- measured against 4,508 real transactions. See eval/README.md.

-- +goose Up

CREATE TABLE categories (
    id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    taxonomy_version text        NOT NULL,

    -- NULL = shared by every organisation. Populated = this organisation's own.
    org_id           uuid        NULL REFERENCES organizations (id) ON DELETE RESTRICT,
    scope            text        NOT NULL CHECK (scope IN ('global', 'org')),

    -- Hierarchical: two characters per level, so a parent's code is its
    -- child's minus the last two. The seed relies on that to resolve parents
    -- without carrying a second key.
    code             text        NOT NULL,
    parent_id        uuid        NULL REFERENCES categories (id) ON DELETE RESTRICT,
    level            smallint    NOT NULL CHECK (level BETWEEN 1 AND 5),
    name             text        NOT NULL,

    pnl_section      text        NULL,
    is_pnl           boolean     NOT NULL DEFAULT true,
    is_leaf          boolean     NOT NULL,

    -- GM, NM, CM, IBT and NI are arithmetic over other lines. A transaction can
    -- never land in one, and change 3.2 must never be offered one as a target.
    is_computed      boolean     NOT NULL DEFAULT false,
    formula          text        NULL,

    -- Payroll is known, the department is not. КНП 332 says "wages" and cannot
    -- say whose; 44 rules and 150 Kazakh rows land here. The report shows the
    -- amount as its own line rather than attributing it to a department.
    requires_allocation boolean  NOT NULL DEFAULT false,

    created_at       timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT categories_scope_matches_owner CHECK (
        (scope = 'global' AND org_id IS NULL) OR (scope = 'org' AND org_id IS NOT NULL)),
    CONSTRAINT categories_computed_has_formula CHECK (
        NOT is_computed OR (formula IS NOT NULL AND is_leaf = false)),

    -- NULLS NOT DISTINCT, or the uniqueness the seed depends on would not
    -- exist for exactly the rows that are shared with everybody: Postgres
    -- treats every NULL org_id as distinct otherwise, and two shared rows
    -- could take the same code.
    CONSTRAINT categories_code_unique
        UNIQUE NULLS NOT DISTINCT (taxonomy_version, org_id, code)
);

CREATE INDEX categories_tenant_idx ON categories (taxonomy_version, org_id);
CREATE INDEX categories_parent_idx ON categories (parent_id);

-- A parent is shared, or it is mine. Never another organisation's.
--
-- This cannot be a composite foreign key, which is what CLAUDE.md requires of
-- referential checks between tenant tables. The legitimate case is an
-- organisation's leaf hanging under a *shared* parent, whose org_id is NULL and
-- therefore never equals the child's. A composite key cannot say "shared or
-- mine".
--
-- A constraint trigger can. It runs as the table owner and sees every row, so
-- it enforces what the key cannot state -- and it closes the same oracle the
-- composite key exists to close, because naming another organisation's category
-- raises the identical error whether that category exists or not.
-- +goose StatementBegin
CREATE FUNCTION categories_parent_is_visible() RETURNS trigger
    LANGUAGE plpgsql
    AS $fn$
DECLARE
    parent_org uuid;
    found      boolean;
BEGIN
    IF NEW.parent_id IS NULL THEN
        RETURN NEW;
    END IF;

    SELECT org_id, true INTO parent_org, found
      FROM categories WHERE id = NEW.parent_id;

    -- One message for "does not exist" and for "belongs to someone else". A
    -- different message for each would report the existence of a row the
    -- caller may not read.
    IF NOT coalesce(found, false) OR (parent_org IS NOT NULL AND parent_org IS DISTINCT FROM NEW.org_id) THEN
        RAISE EXCEPTION 'category parent % is not visible to this organisation', NEW.parent_id
            USING ERRCODE = '23503';
    END IF;
    RETURN NEW;
END
$fn$;
-- +goose StatementEnd

CREATE CONSTRAINT TRIGGER categories_parent_is_visible
    AFTER INSERT OR UPDATE OF parent_id, org_id ON categories
    DEFERRABLE INITIALLY IMMEDIATE
    FOR EACH ROW EXECUTE FUNCTION categories_parent_is_visible();

-- ---------------------------------------------------------------------------
-- The shared rows, seeded BEFORE row-level security is enabled.
--
-- Order is load-bearing. FORCE ROW LEVEL SECURITY subjects the table owner to
-- the policies too, and vekst_migrator is deliberately not a superuser, so once
-- categories_write exists the migrator inserting org_id IS NULL rows is denied
-- by its own policy -- and app_current_org() would raise 42704 first, because
-- a migration sets no tenant context. Seeding here, before the policies, is the
-- only order that works. A test asserts it, since reversing it fails on a fresh
-- database and only for the shared rows.
-- ---------------------------------------------------------------------------

INSERT INTO categories (taxonomy_version, code, scope, org_id, name,
                        level, is_leaf, is_pnl, is_computed, formula, requires_allocation) VALUES
  ('v1', '01', 'global', NULL, 'NET SALES', 1, false, true, false, NULL, false),
  ('v1', '0101', 'global', NULL, 'SOFTWARE DEVELOPMENT', 2, true, true, false, NULL, false),
  ('v1', '02', 'global', NULL, 'CS', 1, true, true, false, NULL, false),
  ('v1', '03', 'global', NULL, 'OCS', 1, false, true, false, NULL, false),
  ('v1', '0301', 'global', NULL, 'PROMOTION', 2, false, true, false, NULL, false),
  ('v1', '04', 'global', NULL, 'OPEX', 1, false, true, false, NULL, false),
  ('v1', '0401', 'global', NULL, 'Administration', 2, false, true, false, NULL, false),
  ('v1', '040101', 'global', NULL, 'Finance', 3, false, true, false, NULL, false),
  ('v1', '04010102', 'global', NULL, 'FI Services', 4, false, true, false, NULL, false),
  ('v1', '0401010201', 'global', NULL, '1С Cloud', 5, true, true, false, NULL, false),
  ('v1', '0401010204', 'global', NULL, 'Bank commission', 5, true, true, false, NULL, false),
  ('v1', '040102', 'global', NULL, 'General Management', 3, false, true, false, NULL, false),
  ('v1', '04010202', 'global', NULL, 'GM Services', 4, false, true, false, NULL, false),
  ('v1', '0401020202', 'global', NULL, 'Communication', 5, true, true, false, NULL, false),
  ('v1', '0401020208', 'global', NULL, 'Office rent', 5, true, true, false, NULL, false),
  ('v1', '040104', 'global', NULL, 'Legal', 3, false, true, false, NULL, false),
  ('v1', '04010401', 'global', NULL, 'Leg. Services', 4, false, true, false, NULL, false),
  ('v1', '0401040101', 'global', NULL, 'Claim', 5, true, true, false, NULL, false),
  ('v1', '0402', 'global', NULL, 'Marketing and Sales', 2, false, true, false, NULL, false),
  ('v1', '0403', 'global', NULL, 'PAYROLL TAX to distribute', 2, true, true, false, NULL, true),
  ('v1', '0404', 'global', NULL, 'PAYROLL to distribute', 2, true, true, false, NULL, true),
  ('v1', '0405', 'global', NULL, 'Production', 2, false, true, false, NULL, false),
  ('v1', '05', 'global', NULL, 'OIE', 1, false, true, false, NULL, false),
  ('v1', '0501', 'global', NULL, 'OTHER EXPENSE', 2, false, true, false, NULL, false),
  ('v1', '050101', 'global', NULL, 'Expenses compensation', 3, true, true, false, NULL, false),
  ('v1', '050103', 'global', NULL, 'Other taxes', 3, false, true, false, NULL, false),
  ('v1', '05010302', 'global', NULL, 'Adv. Tax', 4, true, true, false, NULL, false),
  ('v1', '05010304', 'global', NULL, 'Other', 4, true, true, false, NULL, false),
  ('v1', '05010305', 'global', NULL, 'VAT', 4, true, true, false, NULL, false),
  ('v1', '050104', 'global', NULL, 'Tax fines', 3, true, true, false, NULL, false),
  ('v1', '0502', 'global', NULL, 'OTHER INCOME', 2, false, true, false, NULL, false),
  ('v1', '050202', 'global', NULL, 'Return of payment', 3, true, true, false, NULL, false),
  ('v1', '06', 'global', NULL, 'FR', 1, false, true, false, NULL, false),
  ('v1', '0601', 'global', NULL, 'FXR', 2, false, true, false, NULL, false),
  ('v1', '060101', 'global', NULL, 'Currency exchange', 3, true, true, false, NULL, false),
  ('v1', '060102', 'global', NULL, 'Currency revaluation', 3, true, true, false, NULL, false),
  ('v1', '0602', 'global', NULL, 'OFR', 2, false, true, false, NULL, false),
  ('v1', '060201', 'global', NULL, 'Interests received', 3, true, true, false, NULL, false),
  ('v1', '07', 'global', NULL, 'CIT', 1, true, true, false, NULL, false),
  ('v1', '08', 'global', NULL, 'CAPEX', 1, true, false, false, NULL, false),
  ('v1', '09', 'global', NULL, 'OUT OF P&L', 1, true, false, false, NULL, false),
  ('v1', '91', 'global', NULL, 'GM', 1, false, true, true, 'NET SALES - CS', false),
  ('v1', '92', 'global', NULL, 'NM', 1, false, true, true, 'GM - OCS', false),
  ('v1', '93', 'global', NULL, 'CM', 1, false, true, true, 'NM - OPEX - OIE', false),
  ('v1', '94', 'global', NULL, 'IBT', 1, false, true, true, 'CM - FR', false),
  ('v1', '95', 'global', NULL, 'NI', 1, false, true, true, 'IBT - CIT', false);

-- Codes are hierarchical: two characters per level, so a parent's code is its
-- child's minus the last two. Resolving them here rather than carrying a second
-- key in the seed keeps one thing true instead of two.
UPDATE categories AS c
   SET parent_id = p.id
  FROM categories AS p
 WHERE c.taxonomy_version = p.taxonomy_version
   AND c.org_id IS NULL AND p.org_id IS NULL
   AND length(c.code) > 2
   AND p.code = left(c.code, length(c.code) - 2);

-- ---------------------------------------------------------------------------
-- Row-level security, last.
-- ---------------------------------------------------------------------------

ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories FORCE ROW LEVEL SECURITY;

-- Read: a row that is shared, or mine. Nothing else.
CREATE POLICY categories_read ON categories FOR SELECT
    USING (org_id IS NULL OR org_id = app_current_org());

-- Write: only mine, and only as mine. A shared row arrives by migration and
-- leaves by migration; the application can never create, rename or delete one.
CREATE POLICY categories_write ON categories FOR ALL
    USING      (org_id = app_current_org())
    WITH CHECK (org_id = app_current_org());

-- +goose Down

DROP TABLE categories;
DROP FUNCTION categories_parent_is_visible();
