-- category_templates and currencies: two tables that belong to nobody.
-- Change 5.3 (connect-app-end-to-end), capability `tenancy`.
--
-- category_templates is the industry-specific half of the taxonomy migration
-- 005 could not seed as `categories` rows, because a `categories` row is
-- either shared by every organisation (scope = 'global') or owned by one
-- (scope = 'org') -- there is no third scope for "a starting point every new
-- organisation gets its own copy of". These 60 rows are that starting point:
-- AdoptIndustryTemplate copies them into `categories` as scope = 'org' rows,
-- once, when an organisation is created (core/internal/tenancy).
--
-- currencies closes a gap `add-transaction-ledger` (migration 00007) left
-- open: `organizations.base_currency` and `transactions.currency` validate a
-- currency's three-letter shape only, never whether it names a currency this
-- product actually knows the minor-unit exponent for. Neither existing column
-- gains a foreign key here -- that upgrade is a separate, later change -- but
-- Go validation (tenancy.Service.Create) and any future consumer now have a
-- single, generated source of truth to point at instead of a fact that lived
-- only in core/internal/money.
--
-- Neither table is a tenant table. Neither carries org_id, a policy, or ROW
-- LEVEL SECURITY -- both are exempted in deploy/db/rls-exempt-tables.txt with
-- the same reasoning: a table every organisation reads and none owns is not a
-- gap in the RLS coverage test, it is a table the test cannot classify any
-- other way.

-- +goose Up

-- ---------------------------------------------------------------------------
-- category_templates
-- ---------------------------------------------------------------------------

-- The industry template: the 60 leaves eval/out/industry_template.csv holds.
-- A customer's copy of a template row is an ordinary categories row with
-- scope = 'org' and that customer's org_id, written by AdoptIndustryTemplate
-- under that customer's own policy -- this table itself is never written to
-- by application code, only read from to make that copy.
CREATE TABLE category_templates (
    taxonomy_version text     NOT NULL,
    code             text     NOT NULL,
    parent_code      text     NULL,
    level            smallint NOT NULL CHECK (level BETWEEN 1 AND 5),
    name             text     NOT NULL,
    is_leaf          boolean  NOT NULL,
    is_pnl           boolean  NOT NULL,

    PRIMARY KEY (taxonomy_version, code),

    -- A code is hierarchical, two characters per level, exactly as migration
    -- 005 resolves parents. Stating it here stops a hand-edited row from
    -- carrying a parent_code that its own code contradicts.
    CONSTRAINT category_templates_code_encodes_level
        CHECK (length(code) = level * 2),
    CONSTRAINT category_templates_parent_is_prefix
        CHECK (parent_code IS NULL OR code LIKE parent_code || '__')
);

GRANT SELECT ON category_templates TO vekst_app;

-- Content comes from eval/out/industry_template.sql, generated by
-- eval/emit.py's write_industry_template_sql() from
-- eval/out/industry_template.csv. scripts/check-taxonomy-seed.sh diffs them.
INSERT INTO category_templates (taxonomy_version, code, parent_code, level, name,
                                is_leaf, is_pnl) VALUES
  ('v1', '030101', '0301', 3, 'Prom. Commission', true, true),
  ('v1', '04010101', '040101', 4, 'FI Expenses', false, true),
  ('v1', '0401010101', '04010101', 5, 'Salary', true, true),
  ('v1', '0401010202', '04010102', 5, 'Acc. matters', true, true),
  ('v1', '0401010203', '04010102', 5, 'Audit', true, true),
  ('v1', '0401010205', '04010102', 5, 'E-docs', true, true),
  ('v1', '0401010206', '04010102', 5, 'T&A', true, true),
  ('v1', '04010201', '040102', 4, 'GM Expenses', false, true),
  ('v1', '0401020101', '04010201', 5, 'Salary', true, true),
  ('v1', '0401020201', '04010202', 5, 'BisTrips', true, true),
  ('v1', '0401020203', '04010202', 5, 'Domain', true, true),
  ('v1', '0401020204', '04010202', 5, 'Education', true, true),
  ('v1', '0401020205', '04010202', 5, 'File storage', true, true),
  ('v1', '0401020206', '04010202', 5, 'Hosting', true, true),
  ('v1', '0401020207', '04010202', 5, 'IT equipment repair', true, true),
  ('v1', '0401020209', '04010202', 5, 'Office supplies', true, true),
  ('v1', '0401020210', '04010202', 5, 'Small IT equipment', true, true),
  ('v1', '0401020211', '04010202', 5, 'Sport', true, true),
  ('v1', '0401020212', '04010202', 5, 'Stationary', true, true),
  ('v1', '040103', '0401', 3, 'HR', false, true),
  ('v1', '04010301', '040103', 4, 'HR Services', false, true),
  ('v1', '0401030101', '04010301', 5, 'HR Tools', true, true),
  ('v1', '0401040102', '04010401', 5, 'Court', true, true),
  ('v1', '0401040103', '04010401', 5, 'LE Rent', true, true),
  ('v1', '0401040104', '04010401', 5, 'Legal - other', true, true),
  ('v1', '0401040105', '04010401', 5, 'Relocation', true, true),
  ('v1', '040105', '0401', 3, 'Recruiting', false, true),
  ('v1', '04010501', '040105', 4, 'Rec. Services', false, true),
  ('v1', '0401050101', '04010501', 5, 'Education', true, true),
  ('v1', '0401050102', '04010501', 5, 'HH', true, true),
  ('v1', '040201', '0402', 3, 'Marketing', false, true),
  ('v1', '04020101', '040201', 4, 'MRK Expenses', false, true),
  ('v1', '0402010101', '04020101', 5, 'Salary', true, true),
  ('v1', '04020102', '040201', 4, 'MRK Services', false, true),
  ('v1', '0402010201', '04020102', 5, 'Content creation', true, true),
  ('v1', '0402010202', '04020102', 5, 'Google ADS', true, true),
  ('v1', '0402010203', '04020102', 5, 'MarTech Tools', true, true),
  ('v1', '0402010204', '04020102', 5, 'Marketing Channels', true, true),
  ('v1', '0402010205', '04020102', 5, 'Marketplace adv.', true, true),
  ('v1', '0402010206', '04020102', 5, 'Merch for employees', true, true),
  ('v1', '0402010207', '04020102', 5, 'SEO', true, true),
  ('v1', '040202', '0402', 3, 'Sales', false, true),
  ('v1', '04020201', '040202', 4, 'SL Expenses', false, true),
  ('v1', '0402020101', '04020201', 5, 'Salary', true, true),
  ('v1', '04020202', '040202', 4, 'SL Services', false, true),
  ('v1', '0402020201', '04020202', 5, 'Sales Activities', true, true),
  ('v1', '0402020202', '04020202', 5, 'Sales Tools', true, true),
  ('v1', '040501', '0405', 3, 'Developers', false, true),
  ('v1', '04050101', '040501', 4, 'Dev Expenses', false, true),
  ('v1', '0405010101', '04050101', 5, 'Education', true, true),
  ('v1', '0405010102', '04050101', 5, 'Salary', true, true),
  ('v1', '04050102', '040501', 4, 'Dev Services', false, true),
  ('v1', '0405010201', '04050102', 5, 'Design Tools', true, true),
  ('v1', '0405010202', '04050102', 5, 'Production Tools', true, true),
  ('v1', '0405010203', '04050102', 5, 'Salary', true, true),
  ('v1', '0406', '04', 2, 'Twoj StartUp', true, true),
  ('v1', '050102', '0501', 3, 'Expenses for 2022', true, true),
  ('v1', '05010301', '050103', 4, '1%, IT Park', true, true),
  ('v1', '05010303', '050103', 4, 'IT Park - membership', true, true),
  ('v1', '050201', '0502', 3, 'CIT Refund', true, true);

-- ---------------------------------------------------------------------------
-- currencies
-- ---------------------------------------------------------------------------

-- The ISO-4217 codes this product accepts, and the minor-unit digits each
-- divides into. Seeded from core/internal/money's exponent map, by
-- core/internal/money/cmd/gen-currency-seed. scripts/check-currency-seed.sh
-- diffs the generator's live output against the rows below.
CREATE TABLE currencies (
    code     text     NOT NULL PRIMARY KEY,
    exponent smallint NOT NULL,

    CONSTRAINT currencies_code_shape CHECK (code ~ '^[A-Z]{3}$')
);

GRANT SELECT ON currencies TO vekst_app;

INSERT INTO currencies (code, exponent) VALUES
  ('AED', 2),
  ('AFN', 2),
  ('ALL', 2),
  ('AMD', 2),
  ('ANG', 2),
  ('AOA', 2),
  ('ARS', 2),
  ('AUD', 2),
  ('AWG', 2),
  ('AZN', 2),
  ('BAM', 2),
  ('BBD', 2),
  ('BDT', 2),
  ('BGN', 2),
  ('BHD', 3),
  ('BIF', 0),
  ('BMD', 2),
  ('BND', 2),
  ('BOB', 2),
  ('BOV', 2),
  ('BRL', 2),
  ('BSD', 2),
  ('BTN', 2),
  ('BWP', 2),
  ('BYN', 2),
  ('BZD', 2),
  ('CAD', 2),
  ('CDF', 2),
  ('CHE', 2),
  ('CHF', 2),
  ('CHW', 2),
  ('CLF', 4),
  ('CLP', 0),
  ('CNY', 2),
  ('COP', 2),
  ('COU', 2),
  ('CRC', 2),
  ('CUC', 2),
  ('CUP', 2),
  ('CVE', 2),
  ('CZK', 2),
  ('DJF', 0),
  ('DKK', 2),
  ('DOP', 2),
  ('DZD', 2),
  ('EGP', 2),
  ('ERN', 2),
  ('ETB', 2),
  ('EUR', 2),
  ('FJD', 2),
  ('FKP', 2),
  ('GBP', 2),
  ('GEL', 2),
  ('GHS', 2),
  ('GIP', 2),
  ('GMD', 2),
  ('GNF', 0),
  ('GTQ', 2),
  ('GYD', 2),
  ('HKD', 2),
  ('HNL', 2),
  ('HTG', 2),
  ('HUF', 2),
  ('IDR', 2),
  ('ILS', 2),
  ('INR', 2),
  ('IQD', 3),
  ('IRR', 2),
  ('ISK', 0),
  ('JMD', 2),
  ('JOD', 3),
  ('JPY', 0),
  ('KES', 2),
  ('KGS', 2),
  ('KHR', 2),
  ('KMF', 0),
  ('KPW', 2),
  ('KRW', 0),
  ('KWD', 3),
  ('KYD', 2),
  ('KZT', 2),
  ('LAK', 2),
  ('LBP', 2),
  ('LKR', 2),
  ('LRD', 2),
  ('LSL', 2),
  ('LYD', 3),
  ('MAD', 2),
  ('MDL', 2),
  ('MGA', 2),
  ('MKD', 2),
  ('MMK', 2),
  ('MNT', 2),
  ('MOP', 2),
  ('MRU', 2),
  ('MUR', 2),
  ('MVR', 2),
  ('MWK', 2),
  ('MXN', 2),
  ('MXV', 2),
  ('MYR', 2),
  ('MZN', 2),
  ('NAD', 2),
  ('NGN', 2),
  ('NIO', 2),
  ('NOK', 2),
  ('NPR', 2),
  ('NZD', 2),
  ('OMR', 3),
  ('PAB', 2),
  ('PEN', 2),
  ('PGK', 2),
  ('PHP', 2),
  ('PKR', 2),
  ('PLN', 2),
  ('PYG', 0),
  ('QAR', 2),
  ('RON', 2),
  ('RSD', 2),
  ('RUB', 2),
  ('RWF', 0),
  ('SAR', 2),
  ('SBD', 2),
  ('SCR', 2),
  ('SDG', 2),
  ('SEK', 2),
  ('SGD', 2),
  ('SHP', 2),
  ('SLE', 2),
  ('SOS', 2),
  ('SRD', 2),
  ('SSP', 2),
  ('STN', 2),
  ('SVC', 2),
  ('SYP', 2),
  ('SZL', 2),
  ('THB', 2),
  ('TJS', 2),
  ('TMT', 2),
  ('TND', 3),
  ('TOP', 2),
  ('TRY', 2),
  ('TTD', 2),
  ('TWD', 2),
  ('TZS', 2),
  ('UAH', 2),
  ('UGX', 0),
  ('USD', 2),
  ('USN', 2),
  ('UYI', 0),
  ('UYU', 2),
  ('UYW', 4),
  ('UZS', 2),
  ('VED', 2),
  ('VES', 2),
  ('VND', 0),
  ('VUV', 0),
  ('WST', 2),
  ('XAF', 0),
  ('XAG', 0),
  ('XAU', 0),
  ('XBA', 0),
  ('XBB', 0),
  ('XBC', 0),
  ('XBD', 0),
  ('XCD', 2),
  ('XDR', 0),
  ('XOF', 0),
  ('XPD', 0),
  ('XPF', 0),
  ('XPT', 0),
  ('XSU', 0),
  ('XUA', 0),
  ('YER', 2),
  ('ZAR', 2),
  ('ZMW', 2),
  ('ZWL', 2);

-- +goose Down

DROP TABLE currencies;
DROP TABLE category_templates;
