"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from vekst.internal.v1 import classifier_pb2 as _classifier_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ClassifierServiceStub:
    """ClassifierService is internal: native gRPC on a private ClusterIP Service, called
    only by core. It is never exposed through the Ingress, and it never receives
    database credentials -- ARCHITECTURE.md A-4.

    ClassifyBatch is deliberately absent. Its shapes depend on the taxonomy,
    vendor memory and rule matcher, none of which exist before changes 3.1 and
    3.2. See ../README.md.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ClassifierServiceAsyncStub: ...
    Version: _grpc.UnaryUnaryMultiCallable[_classifier_pb2.VersionRequest, _classifier_pb2.VersionResponse]

@_typing.type_check_only
class ClassifierServiceAsyncStub(ClassifierServiceStub):
    """ClassifierService is internal: native gRPC on a private ClusterIP Service, called
    only by core. It is never exposed through the Ingress, and it never receives
    database credentials -- ARCHITECTURE.md A-4.

    ClassifyBatch is deliberately absent. Its shapes depend on the taxonomy,
    vendor memory and rule matcher, none of which exist before changes 3.1 and
    3.2. See ../README.md.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    Version: _aio.UnaryUnaryMultiCallable[_classifier_pb2.VersionRequest, _classifier_pb2.VersionResponse]  # type: ignore[assignment]

class ClassifierServiceServicer(metaclass=_abc_1.ABCMeta):
    """ClassifierService is internal: native gRPC on a private ClusterIP Service, called
    only by core. It is never exposed through the Ingress, and it never receives
    database credentials -- ARCHITECTURE.md A-4.

    ClassifyBatch is deliberately absent. Its shapes depend on the taxonomy,
    vendor memory and rule matcher, none of which exist before changes 3.1 and
    3.2. See ../README.md.
    """

    @_abc_1.abstractmethod
    def Version(
        self,
        request: _classifier_pb2.VersionRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_classifier_pb2.VersionResponse, _abc.Awaitable[_classifier_pb2.VersionResponse]]: ...

def add_ClassifierServiceServicer_to_server(servicer: ClassifierServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
