# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from vekst.internal.v1 import classifier_pb2 as vekst_dot_internal_dot_v1_dot_classifier__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vekst/internal/v1/classifier_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClassifierServiceStub:
    """ClassifierService is internal: native gRPC on a private ClusterIP Service, called
    only by core. It is never exposed through the Ingress, and it never receives
    database credentials -- ARCHITECTURE.md A-4.

    ClassifyBatch is deliberately absent. Its shapes depend on the taxonomy,
    vendor memory and rule matcher, none of which exist before changes 3.1 and
    3.2. See ../README.md.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Version = channel.unary_unary(
                '/vekst.internal.v1.ClassifierService/Version',
                request_serializer=vekst_dot_internal_dot_v1_dot_classifier__pb2.VersionRequest.SerializeToString,
                response_deserializer=vekst_dot_internal_dot_v1_dot_classifier__pb2.VersionResponse.FromString,
                _registered_method=True)


class ClassifierServiceServicer:
    """ClassifierService is internal: native gRPC on a private ClusterIP Service, called
    only by core. It is never exposed through the Ingress, and it never receives
    database credentials -- ARCHITECTURE.md A-4.

    ClassifyBatch is deliberately absent. Its shapes depend on the taxonomy,
    vendor memory and rule matcher, none of which exist before changes 3.1 and
    3.2. See ../README.md.
    """

    def Version(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClassifierServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Version': grpc.unary_unary_rpc_method_handler(
                    servicer.Version,
                    request_deserializer=vekst_dot_internal_dot_v1_dot_classifier__pb2.VersionRequest.FromString,
                    response_serializer=vekst_dot_internal_dot_v1_dot_classifier__pb2.VersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vekst.internal.v1.ClassifierService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vekst.internal.v1.ClassifierService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClassifierService:
    """ClassifierService is internal: native gRPC on a private ClusterIP Service, called
    only by core. It is never exposed through the Ingress, and it never receives
    database credentials -- ARCHITECTURE.md A-4.

    ClassifyBatch is deliberately absent. Its shapes depend on the taxonomy,
    vendor memory and rule matcher, none of which exist before changes 3.1 and
    3.2. See ../README.md.
    """

    @staticmethod
    def Version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vekst.internal.v1.ClassifierService/Version',
            vekst_dot_internal_dot_v1_dot_classifier__pb2.VersionRequest.SerializeToString,
            vekst_dot_internal_dot_v1_dot_classifier__pb2.VersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
