# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vekst/internal/v1/classifier.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'vekst/internal/v1/classifier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"vekst/internal/v1/classifier.proto\x12\x11vekst.internal.v1\"\x10\n\x0eVersionRequest\";\n\x0fVersionResponse\x12\x16\n\x0e\x65ngine_version\x18\x01 \x01(\t\x12\x10\n\x08\x62uilt_at\x18\x02 \x01(\t2e\n\x11\x43lassifierService\x12P\n\x07Version\x12!.vekst.internal.v1.VersionRequest\x1a\".vekst.internal.v1.VersionResponseBCZAgithub.com/MyauDev/vekst/core/gen/vekstinternal/v1;vektinternalv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vekst.internal.v1.classifier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZAgithub.com/MyauDev/vekst/core/gen/vekstinternal/v1;vektinternalv1'
  _globals['_VERSIONREQUEST']._serialized_start=57
  _globals['_VERSIONREQUEST']._serialized_end=73
  _globals['_VERSIONRESPONSE']._serialized_start=75
  _globals['_VERSIONRESPONSE']._serialized_end=134
  _globals['_CLASSIFIERSERVICE']._serialized_start=136
  _globals['_CLASSIFIERSERVICE']._serialized_end=237
# @@protoc_insertion_point(module_scope)
