"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class VersionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VersionRequest: _TypeAlias = VersionRequest  # noqa: Y015

@_typing.final
class VersionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENGINE_VERSION_FIELD_NUMBER: _builtins.int
    BUILT_AT_FIELD_NUMBER: _builtins.int
    engine_version: _builtins.str
    """Recorded on every classification row from change 3.2 onward, alongside
    taxonomy_version and ruleset_version. Those three strings are what make a
    March report reproduce in June.
    """
    built_at: _builtins.str
    """RFC 3339."""
    def __init__(
        self,
        *,
        engine_version: _builtins.str = ...,
        built_at: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["built_at", b"built_at", "engine_version", b"engine_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VersionResponse: _TypeAlias = VersionResponse  # noqa: Y015
