"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Money(_message.Message):
    """Money is shared by the browser-facing API (vekst.v1) and the classifier's
    internal contract (vekst.internal.v1), which is why it lives in its own
    package rather than either one. It represents an amount as integer minor
    units plus its currency -- never as a floating-point number, in any
    language. ARCHITECTURE.md §6, openspec design D5.
    """

    DESCRIPTOR: _descriptor.Descriptor

    CURRENCY_CODE_FIELD_NUMBER: _builtins.int
    MINOR_UNITS_FIELD_NUMBER: _builtins.int
    currency_code: _builtins.str
    """ISO-4217, uppercase. "EUR", "PLN", "KZT". An unknown code is rejected by
    the application layer against the checked-in currency exponent table --
    never defaulted to an assumed exponent.
    """
    minor_units: _builtins.int
    """Signed amount in the currency's minor units. 1234 with currency_code
    "EUR" is 12.34 EUR. jstype = JS_STRING so this reaches TypeScript as a
    string and never as a JS number, which cannot hold an int64 exactly.
    """
    def __init__(
        self,
        *,
        currency_code: _builtins.str = ...,
        minor_units: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["currency_code", b"currency_code", "minor_units", b"minor_units"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Money: _TypeAlias = Money  # noqa: Y015
